## EN MY SQL CUANDO SALIMOS SE BORRA ##
## ES MEJOR TENER UN BLOC DE NOTAS DONDE COPIAMOS LOS COMANDOS QUE USAMOS, PARA LLEVAR UN REGISTRO ##

# MOSTRAMOS LAS DATABASE #
SHOW DATABASES;
# CREAMOS LA DATABASE #
CREATE DATABASE empresadam;

## CON ESTE COMANDO, ENTRAMOS EFECTIVAMENTE EN LA BASE DE DATOS ##
USE empresadam;

# MOSTRAMOS LAS TABLAS #
SHOW TABLES;

# CREAMOS UNA TABLA
CREATE TABLE clientes(
	dni VARCHAR(9),
	nombre VARCHAR(50),
	apellidos VARCHAR(255),
	email VARCHAR(100)
);
# INSERTAR DATOS EN LA TABLA #
INSERT INTO clientes VALUES(
	"12345678A",
	"Valentin",
	"De Gennaro",
	"valentindegennaro@gmail.com"
);

# MOSTRAMOS TODOS LOS DATOS DE LA TABLA #
SELECT * FROM clientes;

# CAMBIAMOS UN DATO #
UPDATE clientes
SET dni = "11111111A"
WHERE nombre = "Valentin";

UPDATE clientes
SET apellidos = "DeGennaro"
WHERE nombre = "Valentin";

# BORRAMOS UN ELEMENTO DE LA LISTA#
DELETE FROM clientes
WHERE dni = "11111111A";
